Handle sparse data
observablehq/inputs pull request #169
Opened 2021-09-10 21:50 UTC by visnup

Renders empty rows for sparse or falsey rows. Still allows them to be selected.

Also, I found a missing exported test for selectWide which I've included.

2021-09-10 22:12 UTC, mbostock requested changes
I think we should limit this behavior to nullish rather than falsey.

Thanks for improving the tests.

2021-09-10 22:12 UTC, mbostock commented on src/table.js
> +    if (!d) continue;
```suggestion
    if (d == null) continue;
```

2021-09-10 22:12 UTC, mbostock commented on src/table.js
> +      }
```suggestion
    if (d != null) for (let j = 0; j < columns.length; ++j) {
      let column = columns[j];
      let value = d[column];
      if (!defined(value)) continue;
      value = format[column](value, i, data);
      if (!(value instanceof Node)) value = document.createTextNode(value);
      itr.childNodes[j + 1].appendChild(value);
    }
```

2021-09-12 02:54 UTC, mbostock approved these changes

2021-09-13 08:15 UTC, Fil approved these changes

2021-09-14 15:51 UTC, merged